In [18]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv( "income.csv",names=["name","income"], skiprows=[0])
df

      name     income
0    Alice     50,000
1      Bob     60,000
2  Charlie     55,000
3    Diana     52,000
4   Edward     58,000
5    Fiona     45,000
6   George     70,000
7   Hannah     65,000
8    Isaac     48,000
9    Julia  10,00,000

In [20]:
df.describe()

         name  income
count      10      10
unique     10      10
top     Alice  50,000
freq        1       1

In [21]:
print(df.dtypes)

name      object
income    object
dtype: object

In [22]:
df["income"] = df["income"].astype(str)

In [23]:
df["income"] = df["income"].str.replace(",", "", regex=True)
df

      name   income
0    Alice    50000
1      Bob    60000
2  Charlie    55000
3    Diana    52000
4   Edward    58000
5    Fiona    45000
6   George    70000
7   Hannah    65000
8    Isaac    48000
9    Julia  1000000

In [24]:
df["income"] = pd.to_numeric(df["income"], errors="coerce")

In [25]:
df.sort_values(by="income", ascending=True, inplace=True)
print(df)

      name   income
5    Fiona    45000
8    Isaac    48000
0    Alice    50000
3    Diana    52000
2  Charlie    55000
4   Edward    58000
1      Bob    60000
7   Hannah    65000
6   George    70000
9    Julia  1000000

In [26]:
q75 = df["income"].quantile(0.75)
print("75th Percentile:", q75)

75th Percentile: 63750.0

In [27]:
df["income"].quantile(0.50)

56500.0

In [28]:
df["income"].quantile(0.50, interpolation="lower")

55000

In [29]:
df["income"].quantile(1)

1000000.0

In [30]:
df["income"].quantile(0)

45000.0

In [36]:
#using percentile to remove the outlier in dataset
percentile99=df["income"].quantile(0.99)
percentile99
df_no_outlier=df[df.income<percentile99]
df_no_outlier

      name  income
5    Fiona   45000
8    Isaac   48000
0    Alice   50000
3    Diana   52000
2  Charlie   55000
4   Edward   58000
1      Bob   60000
7   Hannah   65000
6   George   70000

In [47]:
#filling a missng value
df["income"][3]=np.NaN

In [48]:
df

      name     income
5    Fiona    45000.0
8    Isaac    48000.0
0    Alice    50000.0
3    Diana        NaN
2  Charlie    55000.0
4   Edward    58000.0
1      Bob    60000.0
7   Hannah    65000.0
6   George    70000.0
9    Julia  1000000.0

In [49]:
#nan substituition
df.income.mean()

161222.22222222222

In [50]:
df_new=df.fillna(df.income.mean())

In [51]:
df_new #because of outlier the nan value is high

      name          income
5    Fiona    45000.000000
8    Isaac    48000.000000
0    Alice    50000.000000
3    Diana   161222.222222
2  Charlie    55000.000000
4   Edward    58000.000000
1      Bob    60000.000000
7   Hannah    65000.000000
6   George    70000.000000
9    Julia  1000000.000000

In [53]:
df_new=df.fillna(df.income.median())
df_new #median

      name     income
5    Fiona    45000.0
8    Isaac    48000.0
0    Alice    50000.0
3    Diana    58000.0
2  Charlie    55000.0
4   Edward    58000.0
1      Bob    60000.0
7   Hannah    65000.0
6   George    70000.0
9    Julia  1000000.0